.gitignore, README.md, composer.json, composer.lock, webpack.config.js, wp-content/themes/theme_name/functions.php, wp-content/themes/theme_name/inc/admin.php, wp-content/themes/theme_name/inc/enqueue.php, wp-content/themes/theme_name/inc/helpers.php, wp-content/themes/theme_name/inc/media.php, wp-content/themes/theme_name/inc/menu.php, wp-content/themes/theme_name/inc/menu/class-walker-texas-ranger.php, wp-content/themes/theme_name/inc/pagination.php, wp-content/themes/theme_name/inc/theme-options.php, wp-content/themes/theme_name/inc/widgets.php
=> Updated composer to include our coding standards

webpack.config.js
This will also trigger reload on changes to php file which is very useful when developing.
=> Add .php to the file extension watch list

wp-content/themes/theme_name/template-parts/header/head.php
=> Fix the validator issue

wp-content/themes/theme_name/inc/enqueue.php
Deregister default jquery and add the cdn one.
Add the correct check for failing `wp_remote_get()`.
=> Fix the enque in case of error

package-lock.json, package.json, wp-content/themes/init_theme_name/skin/assets/scripts/lazyloading.js, wp-content/themes/init_theme_name/skin/assets/scripts/scripts.js, wp-content/themes/init_theme_name/template-parts/single/post.php
This can be used in the same way on image tags and background images
=> implemented lazy loading of images

wp-content/themes/init_theme_name/lib/autoloader.php
Please test before merging. It should work ok, but just to be sure.
=> Fix the autoloader

.github/CONTRIBUTING.md, .github/issue_template.md
A PR for #62 
Readme should be updated once this is merged to master.
Also, we need to equate the develop and master branches, because I got other changes when I tried to merge into develop branch (I made a new branch from master).
=> Add issue template and Contributing template

bin/rename.js, ci-exclude.txt, wp-content/themes/inf_theme/functions.php, wp-content/themes/inf_theme/helpers/class-general-helper.php, wp-content/themes/inf_theme/includes/class-main.php, wp-content/themes/inf_theme/template-parts/header/header.php
problem occurs if you are on https but don't have valid ssl certificate. 
wp_remote_get can't get file and cant show assets and we don't want that
=> adding fix to check if ssl i valid

bin/rename.js
Added additional constants to the rename
=> Update rename script with additional constants

webpack.config.js
Fix addressing issue https://github.com/infinum/wp-boilerplate/issues/128
=> Missing manifest entires while watching fix

README.md
Added a bunch of features that boilerplate uses as well as reference links / explanations where applicable) cause we need to showcase some actual benefits if we are to get people to use this.
Please feel more than free to review / add / change things.
=> Added a "why is boilerplate cool" section.

.travis.yml
- new worker image
- composer self-update is already included
- do not cache non-cacheable dirs
=> Modernize Travis

src/admin/class-modify-admin-appearance.php
=> Improve readability in Modify_Admin_Appearance

phpstan.neon
=> Fix phpstan config

header.php
=> Remove the leading empty line from header

CHANGELOG.md, composer.json, composer.lock, footer.php, header.php, src/admin/class-modify-admin-appearance.php
- Corrections due to movement all src/blocks/layout/... to src/blocks/components in eightshift-frontend-libs
- Updating composer to latest version of eightshift-libs
- class-modify-admin-appearance.php fixed a typo
=> moving layouts folder to components, updating composer

footer.php, header.php, phpcs.xml.dist
Changelog
---
* Converted `header.php` to use components
* Converted `footer.php` to use components
=> Header footer components

CHANGELOG.md, composer.json, composer.lock, footer.php, header.php, package-lock.json, package.json
- Fixing broken build for header
=> fixing broken build

.babelrc, .gitignore, CHANGELOG.md, babel.config.js, package.json, webpack.config.js
- fixing broken build for babel and implemented a breaking change
- added npm scripts for running storybook.
=> Fixing broken build for the latest release

header.php
=> Remove empty PHP tags

src/class-main.php, src/menu/class-menu.php
Discovered by @phpstan on Level max
=> Add two types of class names in get_service_classes()

composer.json
Add correct caret symbol to the minimum PHP version
=> Update caret symbol

header.php
The custom head component wasn't even outputted
=> Output the custom head component

header.php
Adds an ID to the main content block so skip links can target it.
=> Add ID to main content block

footer.php, header.php
Template files had unnecessary escaping for components render.
=> Remove unnecessary escaping in template files

404.php, footer.php, header.php
Changes:
- updated default 404 a bit (might make a component for it, though)
- cleaned up header and footer, replaced with new reusable components
=> Reusable blocks header/footer preparation
